name: 'Rerun CircleCI'
description: 'Reruns a failed CircleCi Job.'
#inputs:
#  user:
#    description: 'user for which to impersonate'
#    required: true
#  repo-token:
#    description: 'github token for creating commit'
#    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
