name: 'Rerun CircleCI'
description: 'Reruns a failed CircleCI Job.'
inputs:
  circleci-token:
    description: 'circleci token for accessing the api'
    required: true
  repo-token:
    description: 'repository token for accessing the api'
    required: true
  users:
    description: 'coma separated list of users for which the workflow should run'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.mjs'
