name: 'Rerun CircleCI'
description: 'Reruns a failed CircleCI Job.'
inputs:
  circleci-token:
    description: 'circleci token for accessing the api'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
